---
name: Transform DSHIP to Event Data

'on':
  workflow_dispatch:
  schedule:
    # Run every 20 minutes
    - cron: '*/20 * * * *'

jobs:
  transform-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.5.1'
          use-public-rspm: true

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev

      - name: Cache R packages
        uses: actions/cache@v4
        with:
          path: ~/.local/share/renv
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: ${{ runner.os }}-renv-

      - name: Restore R environment
        shell: Rscript {0}
        run: |
          if (!requireNamespace("renv", quietly = TRUE)) {
            install.packages("renv")
          }
          renv::restore()

      - name: Run DSHIP transformation script
        shell: Rscript {0}
        env:
          O2A_EXPORT: ${{ vars.O2A_EXPORT }}
        run: |
          source("R/transform_dship_to_event.R")

      - name: Configure git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Commit and push changes
        run: |
          git add data/processed/
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update processed data files [automated]"
            git push
          fi
